# frozen_string_literal: true

module LogisticsApp
  PalletSchema = Dry::Schema.Params do # rubocop:disable Metrics/BlockLength
    optional(:id).filled(:integer)
    optional(:allocated).maybe(:bool)
    optional(:allocated_at).maybe(:time)
    optional(:carton_quantity).maybe(:integer)
    optional(:consignment_note_number).maybe(Types::StrippedString)
    optional(:cooled).maybe(:bool)
    optional(:edi_in_transaction_id).maybe(:integer)
    optional(:exit_ref).maybe(Types::StrippedString)
    optional(:first_cold_storage_at).maybe(:time)
    optional(:govt_first_inspection_at).maybe(:time)
    optional(:govt_inspection_passed).maybe(:bool)
    optional(:govt_reinspection_at).maybe(:time)
    optional(:gross_weight).maybe(:decimal)
    optional(:in_stock).maybe(:bool)
    optional(:inspected).maybe(:bool)
    optional(:inspection_point).maybe(Types::StrippedString)
    optional(:intake_created_at).maybe(:time)
    optional(:internal_inspection_at).maybe(:time)
    optional(:internal_inspection_passed).maybe(:bool)
    optional(:internal_reinspection_at).maybe(:time)
    optional(:nett_weight).maybe(:decimal)
    optional(:on_site_location).maybe(Types::StrippedString)
    optional(:original_consignment_note_number).maybe(Types::StrippedString)
    optional(:original_inspection_point).maybe(Types::StrippedString)
    required(:pallet_number).filled(Types::StrippedString)
    required(:phc).filled(Types::StrippedString)
    optional(:reinspected).maybe(:bool)
    optional(:repacked).maybe(:bool)
    optional(:repacked_at).maybe(:time)
    optional(:scrapped).maybe(:bool)
    optional(:scrapped_at).maybe(:time)
    optional(:shipped).maybe(:bool)
    optional(:shipped_at).maybe(:time)
    optional(:stock_created_at).maybe(:time)
    optional(:temp_tail).maybe(Types::StrippedString)
    optional(:weight_measured_at).maybe(:time)
  end
end
