# frozen_string_literal: true

module LogisticsApp
  PalletSchema = Dry::Schema.Params do # rubocop:disable Metrics/BlockLength
    optional(:id).filled(:integer)
    required(:allocated).maybe(:bool)
    required(:allocated_at).maybe(:time)
    required(:carton_quantity).maybe(:integer)
    required(:consignment_note_number).maybe(Types::StrippedString)
    required(:cooled).maybe(:bool)
    required(:edi_in_transaction_id).maybe(:integer)
    optional(:exit_ref).maybe(Types::StrippedString)
    required(:first_cold_storage_at).maybe(:time)
    required(:govt_first_inspection_at).maybe(:time)
    required(:govt_inspection_passed).maybe(:bool)
    required(:govt_reinspection_at).maybe(:time)
    required(:gross_weight).maybe(:decimal)
    required(:in_stock).maybe(:bool)
    required(:inspected).maybe(:bool)
    required(:inspection_point).maybe(Types::StrippedString)
    required(:intake_created_at).maybe(:time)
    required(:internal_inspection_at).maybe(:time)
    required(:internal_inspection_passed).maybe(:bool)
    required(:internal_reinspection_at).maybe(:time)
    required(:nett_weight).maybe(:decimal)
    required(:on_site_location).maybe(Types::StrippedString)
    required(:original_consignment_note_number).maybe(Types::StrippedString)
    required(:original_inspection_point).maybe(Types::StrippedString)
    required(:pallet_number).filled(Types::StrippedString)
    required(:phc).filled(Types::StrippedString)
    optional(:reinspected).maybe(:bool)
    required(:repacked).maybe(:bool)
    optional(:repacked_at).maybe(:time)
    optional(:scrapped).maybe(:bool)
    required(:scrapped_at).maybe(:time)
    required(:shipped).maybe(:bool)
    optional(:shipped_at).maybe(:time)
    required(:stock_created_at).maybe(:time)
    required(:temp_tail).maybe(Types::StrippedString)
    required(:weight_measured_at).maybe(:time)
  end
end
